/**
 * Fox Schema (foxschema)
 * Copyright 2024-2026 Huy Phan <huyplb@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 *
 * Workflow engine — moved from FoxAgent (packages/pipes/utility/src/script.ts).
 */
import * as z from 'zod';
import type {
  PipeContext,
  RecordBatch,
  TransformPipe,
} from '../../registry/index.js';
import {
  REJECTS_PORT,
  definePipeMetadata,
  errorPolicyField,
  runSandboxed,
  type PipeMetadata,
} from '../../sdk/index.js';

const configSchema = z.object({
  /**
   * Function body over `records` (the batch, as an array of objects) returning
   * the new array. Written by a person in the designer or by an agent — either
   * way it is code the engine did not write, so it never runs in-process.
   */
  script: z
    .string()
    .min(1)
    .max(100_000)
    .describe('Body of a function receiving `records`, returning the new array'),
  /**
   * Hard budget. The worker is terminated when it elapses, which is the only
   * thing that stops a loop that never yields.
   */
  timeoutMs: z.number().int().min(1).max(60_000).default(5_000),
  /** Heap cap for the worker, so runaway allocation dies there, not here. */
  memoryMb: z.number().int().min(16).max(4_096).default(128),
  ...errorPolicyField,
});

/**
 * Run a small transform written as JavaScript.
 *
 * `transform.map` copies dot-paths, which covers renaming and reshaping and
 * nothing else — no arithmetic, no conditionals, no joining two fields. Every
 * comparable platform has an escape hatch for that, and without one a workflow
 * hits a wall that can only be cleared by writing a new pipe.
 *
 * It is also the reason the sandbox exists. This is the one pipe whose body is
 * supplied as *data* — typed into the designer, or generated by an agent
 * extending a workflow — so it runs on a worker thread that the engine can
 * terminate, rather than on the thread every other run shares. A script that
 * loops forever kills its own run and nothing else.
 */
export class ScriptTransformPipe implements TransformPipe {
  readonly type = 'transform.script';
  readonly role = 'transform';

  metadata(): PipeMetadata {
    return definePipeMetadata({
      type: this.type,
      name: 'Script',
      category: 'Transform',
      version: '0.1.0',
      role: 'transform',
      inputs: [{ name: 'in', type: 'records' }],
      outputs: [
        { name: 'out', type: 'records' },
        // Dead-letter, so one bad batch does not have to fail the run.
        { name: REJECTS_PORT, type: 'records' },
      ],
      configSchema,
    });
  }

  validateConfig(config: Record<string, unknown>): void {
    configSchema.parse(config);
  }

  async transform(
    batch: RecordBatch,
    context: PipeContext,
  ): Promise<Map<string, RecordBatch>> {
    const config = configSchema.parse(context.pipe.config);
    const ports = new Map<string, RecordBatch>();

    try {
      const result = await runSandboxed(config.script, batch.records, {
        timeoutMs: config.timeoutMs,
        maxOldGenerationSizeMb: config.memoryMb,
      });
      ports.set('out', { ...batch, records: asRecords(result) });
    } catch (error) {
      if (config.onError === 'fail') throw error;
      // Dead-letter the whole batch: the script failed, so there is no
      // per-record verdict to give — the records are carried through with the
      // reason so nothing is silently dropped.
      ports.set(REJECTS_PORT, {
        ...batch,
        id: `${batch.id}:rejects`,
        records: batch.records.map((record) => ({
          ...record,
          _error: (error as Error).message,
        })),
        // Cursor-less like every dead-letter batch: a checkpoint may only
        // advance through data.
        cursor: undefined,
      });
    }

    return ports;
  }
}

/**
 * A sandboxed script can return anything. Anything that is not an array of
 * objects is a bug in the script, and saying so beats letting a string or a
 * `null` travel downstream as if it were a batch.
 */
function asRecords(value: unknown): Record<string, unknown>[] {
  if (!Array.isArray(value)) {
    throw new Error(
      `transform.script must return an array of records, got ${describe(value)}`,
    );
  }
  return value.map((entry, index) => {
    if (entry === null || typeof entry !== 'object' || Array.isArray(entry)) {
      throw new Error(
        `transform.script returned ${describe(entry)} at index ${index}; every entry must be an object`,
      );
    }
    return entry as Record<string, unknown>;
  });
}

function describe(value: unknown): string {
  if (value === null) return 'null';
  if (Array.isArray(value)) return 'an array';
  return typeof value;
}
