/**
 * Fox Schema (@foxschema/sql)
 * Copyright 2024-2026 Huy Phan <huyplb@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 *
 * The same command in the shape the reader actually needs: run directly, run
 * against a container, or saved as a script.
 */
import type { GeneratedCommand } from './cli.types.js';
import { heredoc } from './shell.js';

export type CommandFormat =
  /** The client invoked directly, for a client installed on this machine. */
  | 'raw'
  /** The same thing inside `docker exec`, for a containerised server. */
  | 'docker'
  /** A `.sh` file to save, review and run. */
  | 'script';

export interface FormatOptions {
  format: CommandFormat;
  /** Container name or id. Required for `docker`. */
  container?: string;
}

export interface FormattedCommand {
  text: string;
  /** Suggested file name, for the format that produces a file. */
  filename?: string;
}

/** Docker accepts these in a name or id; anything else is a paste accident. */
const SAFE_CONTAINER = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;

/**
 * Re-wrap a built command.
 *
 * Rebuilt from {@link GeneratedCommand.invocation} and `body` rather than by
 * editing the finished string: the heredoc has to stay the last thing on the
 * line, and finding that by pattern would break the first time a statement
 * contained something that looked like a delimiter.
 */
export function formatCommand(
  generated: GeneratedCommand,
  options: FormatOptions
): FormattedCommand | { error: string } {
  if (options.format === 'raw') {
    return { text: generated.command };
  }

  if (options.format === 'docker') {
    const container = (options.container ?? '').trim();
    if (!container) return { error: 'Enter the container name to run this inside.' };
    if (!SAFE_CONTAINER.test(container)) {
      return {
        error:
          'Container name may hold letters, digits, dot, dash and underscore, and must start with a letter or digit.',
      };
    }
    // -i keeps stdin open. Without it the heredoc is discarded and the client
    // reads nothing, which looks like a command that ran and did nothing.
    const wrapped = heredoc(`docker exec -i ${container} ${generated.invocation}`, generated.body);
    if (typeof wrapped !== 'string') return wrapped;
    return { text: wrapped };
  }

  return {
    text: scriptFor(generated),
    filename: `foxschema-${generated.client.replace(/[^a-z0-9]+/gi, '-')}.sh`,
  };
}

function scriptFor(generated: GeneratedCommand): string {
  const lines = [
    '#!/usr/bin/env bash',
    '#',
    '# Generated by Fox Schema. Read it before you run it.',
    `# Needs ${generated.client} on PATH.`,
  ];

  if (generated.auth === 'prompts') {
    lines.push('#', `# ${generated.client} asks for the password. That prompt is not a hang.`);
  }
  if (generated.auth === 'environment' && generated.envVar) {
    lines.push('#', `# Set ${generated.envVar} before running, or let the client prompt.`);
  }
  if (generated.note) lines.push('#', `# ${generated.note}`);

  lines.push(
    '',
    // -e stop on error, -u catch an unset variable, pipefail so a failure in
    // the middle of a pipe is not hidden by a later success.
    'set -euo pipefail',
    '',
    generated.command,
    ''
  );
  return lines.join('\n');
}
