-- FoxSchema ADVANCED seed — IBM DB2 12
-- Schema pair in foxdb: DEMO_C (source) vs DEMO_D (target). Run via db2 -tvf.
-- Case matrix: see scripts/seed/advanced/postgres.sql (B1–B14).
-- DB2 deviations:
--   B4 skipped — DB2 has no per-column collation.
--   B6 is a REAL MQT here (DATA INITIALLY DEFERRED REFRESH DEFERRED) — the one
--      non-Postgres dialect where FoxSchema detects materialized query tables.
-- `--#SET TERMINATOR @` switches the CLP terminator around compound blocks.
-- Load via: bash scripts/seed/seed-advanced.sh db2

-- Drop everything from a previous run (order matters: dependents first)
--#SET TERMINATOR @
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
  EXECUTE IMMEDIATE 'DROP VIEW DEMO_C.V_ORPHAN';
  EXECUTE IMMEDIATE 'DROP VIEW DEMO_C.V_SHIPMENT_STATUS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_C.MV_DAILY_SALES';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_C.T_ONLY_IN_C';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_C.T_TIME_PRECISION';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_C.T_CHECKS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_C.AUDIT_EVENTS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_C.INVENTORY';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_C.T_ALL_TYPES';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_C.EMPLOYEES';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_C.SHIPMENTS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_C.WAREHOUSES';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_C.REGIONS';
  EXECUTE IMMEDIATE 'DROP SEQUENCE DEMO_C.SEQ_BATCH';
  EXECUTE IMMEDIATE 'DROP FUNCTION DEMO_C.FN_SHIP_COST';
  EXECUTE IMMEDIATE 'DROP PROCEDURE DEMO_C.SP_RESTOCK';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_D.T_DEPRECATED_CACHE';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_D.T_TIME_PRECISION';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_D.T_CHECKS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_D.AUDIT_EVENTS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_D.INVENTORY';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_D.T_ALL_TYPES';
  EXECUTE IMMEDIATE 'DROP SEQUENCE DEMO_D.SEQ_BATCH';
  EXECUTE IMMEDIATE 'DROP FUNCTION DEMO_D.FN_SHIP_COST';
END@
--#SET TERMINATOR ;

-- ============================================================
-- DEMO_C (source)
-- ============================================================

-- [B5] Sequence with every attribute set
CREATE SEQUENCE DEMO_C.SEQ_BATCH START WITH 500 INCREMENT BY 5 MINVALUE 1 MAXVALUE 1000000 CACHE 20 CYCLE;

-- [B1] Three-level FK chain
CREATE TABLE DEMO_C.REGIONS (
    ID   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE CHAR(3)      NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CONSTRAINT UQ_REGIONS_CODE UNIQUE (CODE)
);
CREATE TABLE DEMO_C.WAREHOUSES (
    ID        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REGION_ID INT NOT NULL,
    NAME      VARCHAR(120) NOT NULL,
    CAPACITY  INT NOT NULL DEFAULT 1000,
    CONSTRAINT FK_WH_REGION FOREIGN KEY (REGION_ID) REFERENCES DEMO_C.REGIONS(ID)
);
CREATE TABLE DEMO_C.SHIPMENTS (
    ID           INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    WAREHOUSE_ID INT NOT NULL,
    TRACKING_NO  VARCHAR(40) NOT NULL,
    WEIGHT_KG    DECIMAL(8,2) NOT NULL,
    SHIPPED_AT   TIMESTAMP,
    CONSTRAINT UQ_SHIP_TRACK UNIQUE (TRACKING_NO),
    CONSTRAINT FK_SHIP_WH FOREIGN KEY (WAREHOUSE_ID) REFERENCES DEMO_C.WAREHOUSES(ID)
);
CREATE INDEX DEMO_C.IDX_C_SHIPMENTS_WH ON DEMO_C.SHIPMENTS(WAREHOUSE_ID);

-- [B2] Self-referencing FK
CREATE TABLE DEMO_C.EMPLOYEES (
    ID         INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME       VARCHAR(150) NOT NULL,
    MANAGER_ID INT,
    CONSTRAINT FK_EMP_MGR FOREIGN KEY (MANAGER_ID) REFERENCES DEMO_C.EMPLOYEES(ID)
);

-- [B3] Portable type matrix
CREATE TABLE DEMO_C.T_ALL_TYPES (
    ID          INT NOT NULL PRIMARY KEY,
    C_SMALLINT  SMALLINT,
    C_INTEGER   INTEGER,
    C_BIGINT    BIGINT,
    C_DECIMAL   DECIMAL(12,4),
    C_CHAR      CHAR(8),
    C_VARCHAR   VARCHAR(120),
    C_TEXT      CLOB,
    C_BLOB      BLOB,
    C_DATE      DATE,
    C_TS        TIMESTAMP
);

-- [B7] Composite unique + named FK with ON DELETE CASCADE
CREATE TABLE DEMO_C.INVENTORY (
    ID           INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    WAREHOUSE_ID INT NOT NULL,
    SKU          VARCHAR(50) NOT NULL,
    QTY          INT NOT NULL DEFAULT 0,
    CONSTRAINT UQ_INVENTORY_WH_SKU UNIQUE (WAREHOUSE_ID, SKU),
    CONSTRAINT FK_INVENTORY_WH FOREIGN KEY (WAREHOUSE_ID) REFERENCES DEMO_C.WAREHOUSES(ID) ON DELETE CASCADE
);

-- [B8] Identity PK (DEMO_D has a plain INT)
CREATE TABLE DEMO_C.AUDIT_EVENTS (
    ID         INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    PAYLOAD    CLOB,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
);

-- [B11] CHECK constraints — identical in both schemas
CREATE TABLE DEMO_C.T_CHECKS (
    ID    INT NOT NULL PRIMARY KEY,
    QTY   INT NOT NULL CHECK (QTY >= 0),
    PRICE DECIMAL(10,2) CHECK (PRICE > 0)
);

-- [B12] Timestamp precision
CREATE TABLE DEMO_C.T_TIME_PRECISION (
    ID  INT NOT NULL PRIMARY KEY,
    TS3 TIMESTAMP(3),
    TS6 TIMESTAMP(6)
);

-- [B10] Skip-failures pair
CREATE TABLE DEMO_C.T_ONLY_IN_C (
    ID   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOTE VARCHAR(200)
);
CREATE VIEW DEMO_C.V_ORPHAN AS
SELECT ID, NOTE FROM DEMO_C.T_ONLY_IN_C WHERE NOTE IS NOT NULL;

CREATE VIEW DEMO_C.V_SHIPMENT_STATUS AS
SELECT S.ID, S.TRACKING_NO, S.WEIGHT_KG, W.NAME AS WAREHOUSE, R.CODE AS REGION
FROM   DEMO_C.SHIPMENTS S
JOIN   DEMO_C.WAREHOUSES W ON W.ID = S.WAREHOUSE_ID
JOIN   DEMO_C.REGIONS R    ON R.ID = W.REGION_ID;

-- [B9] Two-parameter routine + procedure
--#SET TERMINATOR @
CREATE FUNCTION DEMO_C.FN_SHIP_COST(P_WEIGHT DECIMAL(8,2), P_ZONE INT)
RETURNS DECIMAL(10,2)
LANGUAGE SQL DETERMINISTIC NO EXTERNAL ACTION
RETURN P_WEIGHT * 2.5 * P_ZONE@

CREATE PROCEDURE DEMO_C.SP_RESTOCK(IN P_WAREHOUSE INT, IN P_SKU VARCHAR(50), IN P_QTY INT)
LANGUAGE SQL
BEGIN
  UPDATE DEMO_C.INVENTORY SET QTY = QTY + P_QTY
  WHERE WAREHOUSE_ID = P_WAREHOUSE AND SKU = P_SKU;
END@

-- [B14] Trigger on the ADDED shipments table
CREATE TRIGGER DEMO_C.TRG_SHIPMENTS_TOUCH
BEFORE INSERT ON DEMO_C.SHIPMENTS
REFERENCING NEW AS N FOR EACH ROW
WHEN (N.SHIPPED_AT IS NULL)
SET N.SHIPPED_AT = CURRENT TIMESTAMP@
--#SET TERMINATOR ;

-- Sample data
INSERT INTO DEMO_C.REGIONS (CODE, NAME) VALUES ('EMA', 'Europe/Middle East'), ('APA', 'Asia Pacific'), ('AMR', 'Americas');
INSERT INTO DEMO_C.WAREHOUSES (REGION_ID, NAME, CAPACITY) VALUES (1, 'Rotterdam Hub', 5000), (2, 'Singapore Hub', 8000);
INSERT INTO DEMO_C.SHIPMENTS (WAREHOUSE_ID, TRACKING_NO, WEIGHT_KG) VALUES (1, 'TRK-0001', 12.50), (1, 'TRK-0002', 3.75), (2, 'TRK-0003', 140.00);
INSERT INTO DEMO_C.EMPLOYEES (NAME, MANAGER_ID) VALUES ('Ava CEO', NULL);
INSERT INTO DEMO_C.EMPLOYEES (NAME, MANAGER_ID) VALUES ('Ben Lead', 1);
INSERT INTO DEMO_C.EMPLOYEES (NAME, MANAGER_ID) VALUES ('Cy Dev', 2);
INSERT INTO DEMO_C.T_ALL_TYPES (ID, C_SMALLINT, C_INTEGER, C_BIGINT, C_DECIMAL, C_CHAR, C_VARCHAR, C_TEXT, C_DATE, C_TS)
VALUES (1, 1, 100, 10000000000, 1234.5678, 'ABC', 'hello', 'lorem ipsum', '2026-01-15', '2026-01-15 10:30:00');
INSERT INTO DEMO_C.INVENTORY (WAREHOUSE_ID, SKU, QTY) VALUES (1, 'SKU-RED', 25), (2, 'SKU-BLU', 60);
INSERT INTO DEMO_C.T_ONLY_IN_C (NOTE) VALUES ('only exists in demo_c');

-- [B6] Real MQT — FoxSchema surfaces this as objectType MQT
CREATE TABLE DEMO_C.MV_DAILY_SALES AS (
  SELECT S.WAREHOUSE_ID, COUNT(*) AS SHIPMENT_COUNT, SUM(S.WEIGHT_KG) AS TOTAL_WEIGHT
  FROM DEMO_C.SHIPMENTS S
  GROUP BY S.WAREHOUSE_ID
) DATA INITIALLY DEFERRED REFRESH DEFERRED;
REFRESH TABLE DEMO_C.MV_DAILY_SALES;

-- ============================================================
-- DEMO_D (target)
-- ============================================================

-- [B5] Same sequence name, different attributes
CREATE SEQUENCE DEMO_D.SEQ_BATCH START WITH 1 INCREMENT BY 1 NO CACHE NO CYCLE;

-- [B3] Narrowed/drifted type matrix
CREATE TABLE DEMO_D.T_ALL_TYPES (
    ID          INT NOT NULL PRIMARY KEY,
    C_SMALLINT  SMALLINT,
    C_INTEGER   INTEGER,
    C_BIGINT    INTEGER,
    C_DECIMAL   DECIMAL(14,6),
    C_CHAR      CHAR(8),
    C_VARCHAR   VARCHAR(200),
    C_TEXT      CLOB,
    C_DATE      DATE,
    C_TS        TIMESTAMP,
    C_LEGACY    VARCHAR(20)
);

-- [B7] Weaker unique, no FK
CREATE TABLE DEMO_D.INVENTORY (
    ID           INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    WAREHOUSE_ID INT NOT NULL,
    SKU          VARCHAR(50) NOT NULL,
    QTY          INT NOT NULL DEFAULT 0,
    CONSTRAINT UQ_INVENTORY_WH_SKU UNIQUE (WAREHOUSE_ID)
);

-- [B8] Plain INT PK — no identity
CREATE TABLE DEMO_D.AUDIT_EVENTS (
    ID         INT NOT NULL PRIMARY KEY,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    PAYLOAD    CLOB,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
);

-- [B11] Identical CHECKs
CREATE TABLE DEMO_D.T_CHECKS (
    ID    INT NOT NULL PRIMARY KEY,
    QTY   INT NOT NULL CHECK (QTY >= 0),
    PRICE DECIMAL(10,2) CHECK (PRICE > 0)
);

-- [B12] TS3 precision differs
CREATE TABLE DEMO_D.T_TIME_PRECISION (
    ID  INT NOT NULL PRIMARY KEY,
    TS3 TIMESTAMP(6),
    TS6 TIMESTAMP(6)
);

-- [B9] One-parameter signature
--#SET TERMINATOR @
CREATE FUNCTION DEMO_D.FN_SHIP_COST(P_WEIGHT DECIMAL(8,2))
RETURNS DECIMAL(10,2)
LANGUAGE SQL DETERMINISTIC NO EXTERNAL ACTION
RETURN P_WEIGHT * 3.0@
--#SET TERMINATOR ;

-- [B13] Target-only table → REMOVED
CREATE TABLE DEMO_D.T_DEPRECATED_CACHE (
    CACHE_KEY  VARCHAR(100) NOT NULL PRIMARY KEY,
    CACHE_VAL  CLOB,
    EXPIRES_AT TIMESTAMP
);
