// Single source of truth for engine types: re-exported from @foxschema/sql,
// which is pure by construction (no Node built-ins, no deps), so the frontend
// bundle stays clean — no need to maintain a hand-kept duplicate here.
export type {
  DbObjectType,
  DiffType,
  RoutineParameterMode,
  RoutineParameter,
  ColumnInfo,
  IndexInfo,
  ForeignKeyInfo,
  PrimaryKeyInfo,
  TriggerInfo,
  SequenceInfo,
  UserTypeInfo,
  TableSchema,
  ColumnDiff,
  IndexDiff,
  ForeignKeyDiff,
  TriggerDiff,
  TableDiff,
  SchemaCompareResult,
  MigrationStep,
  MigrationEvent,
  DriverInfo,
  SavedConnection,
} from '@foxschema/sql';
