/**
 * Thin re-export facade over `@foxschema/sql` for the Database Access
 * Assistant. Frontend code imports from here, never from `@foxschema/db`.
 */
export {
  ACCESS_PERMISSIONS,
  ACCESS_PRESETS,
  PERMISSION_DESCRIPTORS,
  PERMISSION_RISK,
  accessCapabilities,
  accessFamily,
  availablePermissions,
  buildAccessSql,
  buildUserSql,
  buildDb2OsUserInstructions,
  osAccountSteps,
  DB2_DOCKER_CONTAINER,
  generateDb2OsPassword,
  validateDb2OsPassword,
  DB2_OS_PASSWORD_LENGTH,
  userManagementSupport,
  PASSWORD_PLACEHOLDER,
  describePermission,
  highestRisk,
  invertAccessRequest,
  diffAccessDesired,
  buildAccessReconciliationSql,
  permissionsForPreset,
  presetForPermissions,
  supportsAccessBuilder,
  type AccessCapabilities,
  type AccessPermission,
  type AccessPreset,
  type AccessPrincipal,
  type AccessScope,
  type AccessDesiredState,
  type AccessDiffEntry,
  type AccessDiffResult,
  type AccessDiffStatus,
  type AccessWarningLevel,
  type GeneratedPermissionSql,
  type GeneratedStatement,
  type PermissionDescriptor,
  type PermissionRequest,
  type PermissionRisk,
  type PermissionWarning,
  type GeneratedUserSql,
  type PrincipalType,
  DEFAULT_DB2_RUN_MODE,
  type Db2RunMode,
  type OsAccountSteps,
  type UserAction,
  type UserAlteration,
  type UserManagementSupport,
  type UserRequest,
  permissionsForPrivilege,
  resolveEffectiveAccess,
  resolveRoleChain,
  type AccessSource,
  type AccessSourceKind,
  type EffectiveAccess,
  type EffectiveEntry,
  type EffectiveObject,
  buildAccessReport,
  principalsWithAccessTo,
  dialectSupportsDbAccess,
  privilegesForPrincipal,
  type AccessFinding,
  type AccessReport,
  type PrincipalAccessRow,
  type DbPrincipal,
  type DbPrincipalKind,
  type DbPrivilege,
} from '@foxschema/sql';
