-- FoxSchema demo seed — DB2 LUW
-- Two schemas in foxdb: DEMO_A (source, newer) vs DEMO_B (target, older)
-- Scopes covered: Tables, Views, Indexes (functions/procedures/triggers: TODO)
--
-- Run via the DB2 community image's /var/custom auto-init hook (see
-- docker/init/db2/01_seed.sh) — NOT auto-run by docker-entrypoint-initdb.d
-- like Postgres/MySQL; DB2's image has its own convention.
--
-- CLP terminator note: the default statement terminator is `;`, which breaks
-- compound SQL PL blocks (BEGIN ... END) containing their own `;`-terminated
-- inner statements — the CLP would split on every inner `;`, not just the
-- block's closing one. `--#SET TERMINATOR @` switches the terminator for the
-- block only; switch back to `;` immediately after for the plain statements
-- that follow. Same class of gotcha as MySQL's DELIMITER $$.

-- ============================================================
-- SCHEMA A (source — complete, newer version)
-- ============================================================

-- Drop tables if they exist, to allow clean reseeding.
--#SET TERMINATOR @
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_A.ORDER_ITEMS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_A.ORDERS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_A.PRODUCTS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_A.EMPLOYEE_ROLES';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_A.CUSTOMERS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_A.CATEGORIES';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_A.INVENTORY';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_A.COUPONS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_A.INTERNATIONAL_SETTINGS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_A.WEB_LOGS';
  EXECUTE IMMEDIATE 'DROP VIEW DEMO_A.V_CUSTOMER_ORDERS';
  EXECUTE IMMEDIATE 'DROP VIEW DEMO_A.V_LOW_STOCK';
END@
--#SET TERMINATOR ;

CREATE TABLE DEMO_A.CATEGORIES (
    ID          INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NAME        VARCHAR(100) NOT NULL,
    SLUG        VARCHAR(100) NOT NULL UNIQUE,
    PARENT_ID   INT
);

CREATE TABLE DEMO_A.CUSTOMERS (
    ID          INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NAME        VARCHAR(150) NOT NULL,
    EMAIL       VARCHAR(255) NOT NULL UNIQUE,
    PHONE       VARCHAR(20),
    TIER        VARCHAR(10) NOT NULL DEFAULT 'standard',
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
);

CREATE TABLE DEMO_A.PRODUCTS (
    ID          INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NAME        VARCHAR(200) NOT NULL,
    SKU         VARCHAR(50)  NOT NULL UNIQUE,
    PRICE       DECIMAL(10,2) NOT NULL,
    STOCK       INT NOT NULL DEFAULT 0,
    CATEGORY_ID INT,
    ACTIVE      SMALLINT NOT NULL DEFAULT 1,
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES DEMO_A.CATEGORIES(ID)
);

CREATE TABLE DEMO_A.ORDERS (
    ID          INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    TOTAL       DECIMAL(12,2) NOT NULL,
    STATUS      VARCHAR(20) NOT NULL DEFAULT 'pending',
    NOTES       CLOB,
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES DEMO_A.CUSTOMERS(ID)
);

CREATE TABLE DEMO_A.ORDER_ITEMS (
    ID          INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    ORDER_ID    INT NOT NULL,
    PRODUCT_ID  INT NOT NULL,
    QTY         INT NOT NULL DEFAULT 1,
    UNIT_PRICE  DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_ITEM_ORDER   FOREIGN KEY (ORDER_ID)   REFERENCES DEMO_A.ORDERS(ID),
    CONSTRAINT FK_ITEM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES DEMO_A.PRODUCTS(ID)
);

-- Case 1: Column reordering & column type mutation
CREATE TABLE DEMO_A.INVENTORY (
    ID           INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    WAREHOUSE    VARCHAR(50) NOT NULL,
    BIN_LOCATION VARCHAR(20),
    QUANTITY     BIGINT NOT NULL DEFAULT 0,
    LAST_COUNTED TIMESTAMP
);

-- Case 2: Constraint name mismatch
CREATE TABLE DEMO_A.EMPLOYEE_ROLES (
    EMP_ID  INT NOT NULL,
    ROLE_ID INT NOT NULL,
    PRIMARY KEY (EMP_ID, ROLE_ID),
    CONSTRAINT FK_ACTIVE_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES DEMO_A.CUSTOMERS(ID)
);

-- Case 3: Expression defaults & generated columns (DB2 uses GENERATED ALWAYS AS)
CREATE TABLE DEMO_A.COUPONS (
    ID           INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    CODE         VARCHAR(50) NOT NULL,
    DISCOUNT     DECIMAL(5,2) NOT NULL,
    DISPLAY_NAME VARCHAR(100) GENERATED ALWAYS AS (CODE || ' (-' || CHAR(DISCOUNT) || '%)')
);

-- Case 4: Collations & column comments sync
CREATE TABLE DEMO_A.INTERNATIONAL_SETTINGS (
    ID           INT PRIMARY KEY NOT NULL,
    SETTING_KEY  VARCHAR(50) NOT NULL,
    SETTING_VAL  VARCHAR(1000)
);
COMMENT ON COLUMN DEMO_A.INTERNATIONAL_SETTINGS.SETTING_VAL IS 'JSON string payload configuration';

-- Case 5: Composite index order variation
CREATE TABLE DEMO_A.WEB_LOGS (
    ID          BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    IP_ADDRESS  VARCHAR(45) NOT NULL,
    STATUS_CODE INT NOT NULL,
    LOGGED_AT   TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- Performance core indices
CREATE INDEX DEMO_A.IDX_PRODUCTS_CAT ON DEMO_A.PRODUCTS(CATEGORY_ID);
CREATE INDEX DEMO_A.IDX_PRODUCTS_SKU ON DEMO_A.PRODUCTS(SKU);
CREATE INDEX DEMO_A.IDX_ORDERS_CUST  ON DEMO_A.ORDERS(CUSTOMER_ID);
CREATE INDEX DEMO_A.IDX_ORDERS_STAT  ON DEMO_A.ORDERS(STATUS);
CREATE INDEX DEMO_A.IDX_ITEMS_ORD    ON DEMO_A.ORDER_ITEMS(ORDER_ID);

-- Case 5 specific index configuration (STATUS_CODE first)
CREATE INDEX DEMO_A.IDX_PERF_COMPOSITE ON DEMO_A.WEB_LOGS(STATUS_CODE, IP_ADDRESS);

-- Views
CREATE VIEW DEMO_A.V_CUSTOMER_ORDERS AS
SELECT c.id AS customer_id, c.name, c.email, c.tier,
       COUNT(o.id)              AS order_count,
       COALESCE(SUM(o.total),0) AS total_spent
FROM   DEMO_A.CUSTOMERS c
LEFT JOIN DEMO_A.ORDERS o ON o.customer_id = c.id
GROUP BY c.id, c.name, c.email, c.tier;

CREATE VIEW DEMO_A.V_LOW_STOCK AS
SELECT id, name, sku, stock, category_id
FROM   DEMO_A.PRODUCTS
WHERE  stock < 10 AND active = 1;

-- ============================================================
-- SCHEMA B (target — older version, intentional differences)
-- ============================================================

--#SET TERMINATOR @
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' BEGIN END;
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_B.ORDER_ITEMS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_B.ORDERS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_B.PRODUCTS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_B.EMPLOYEE_ROLES';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_B.CUSTOMERS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_B.INVENTORY';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_B.COUPONS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_B.INTERNATIONAL_SETTINGS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_B.WEB_LOGS';
  EXECUTE IMMEDIATE 'DROP TABLE DEMO_B.LEGACY_AUDIT_LOG';
  EXECUTE IMMEDIATE 'DROP VIEW DEMO_B.V_ORDER_SUMMARY';
END@
--#SET TERMINATOR ;

-- Missing: DEMO_B.CATEGORIES table entirely

CREATE TABLE DEMO_B.CUSTOMERS (
    ID    INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NAME  VARCHAR(100) NOT NULL,        -- shorter length (was 150)
    EMAIL VARCHAR(255) NOT NULL UNIQUE
    -- missing: phone, tier, created_at
);

CREATE TABLE DEMO_B.PRODUCTS (
    ID    INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    NAME  VARCHAR(200) NOT NULL,
    -- PRICE kept as DECIMAL(10,2) to match demo_a: a DB2 column TYPE change
    -- (SET DATA TYPE) puts the table in reorg-pending (SQL0668N rc=7), which
    -- blocks the rest of the same-transaction ALTERs. Type-change coverage
    -- lives in the other 5 dialects' seeds; DB2 exercises column ADD / FK /
    -- index / generated-column paths instead.
    PRICE DECIMAL(10,2) NOT NULL,
    STOCK INT NOT NULL DEFAULT 0
    -- missing: sku, category_id, active, created_at
);

CREATE TABLE DEMO_B.ORDERS (
    ID          INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    TOTAL       DECIMAL(12,2) NOT NULL,
    STATUS      VARCHAR(20) NOT NULL DEFAULT 'pending',
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP
    -- missing: notes
);

CREATE TABLE DEMO_B.ORDER_ITEMS (
    ID          INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    ORDER_ID    INT NOT NULL,
    PRODUCT_ID  INT NOT NULL,
    QTY         INT NOT NULL DEFAULT 1,
    UNIT_PRICE  DECIMAL(10,2) NOT NULL
    -- missing: FK constraints
);

-- INVENTORY: QUANTITY kept as BIGINT to match demo_a (avoid the reorg-pending
-- type change, same as PRODUCTS above). Still exercises ADD COLUMN (last_counted).
CREATE TABLE DEMO_B.INVENTORY (
    ID           INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    WAREHOUSE    VARCHAR(50) NOT NULL,
    QUANTITY     BIGINT NOT NULL DEFAULT 0,
    BIN_LOCATION VARCHAR(20)
    -- missing column: last_counted
);

-- EMPLOYEE_ROLES: same shape and same FK name as demo_a → no diff.
-- (A constraint-NAME-only rename is inherently a DROP+ADD; non-destructive mode
-- keeps the old FK, so adding a same-columns FK under a new name is a duplicate
-- constraint that DB2 rejects (SQL0541W). That scenario belongs in a
-- destructive-mode test, not the non-destructive E2E flow.)
CREATE TABLE DEMO_B.EMPLOYEE_ROLES (
    EMP_ID  INT NOT NULL,
    ROLE_ID INT NOT NULL,
    PRIMARY KEY (EMP_ID, ROLE_ID),
    CONSTRAINT FK_ACTIVE_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES DEMO_B.CUSTOMERS(ID)
);

-- Case 3: missing generated/derived column
CREATE TABLE DEMO_B.COUPONS (
    ID           INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    CODE         VARCHAR(50) NOT NULL,
    DISCOUNT     DECIMAL(5,2) NOT NULL
);

-- Case 4: missing column comment
CREATE TABLE DEMO_B.INTERNATIONAL_SETTINGS (
    ID           INT PRIMARY KEY NOT NULL,
    SETTING_KEY  VARCHAR(50) NOT NULL,
    SETTING_VAL  VARCHAR(1000)
);

CREATE TABLE DEMO_B.WEB_LOGS (
    ID          BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    IP_ADDRESS  VARCHAR(45) NOT NULL,
    STATUS_CODE INT NOT NULL,
    LOGGED_AT   TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- Orphan table (present in target, absent in source)
CREATE TABLE DEMO_B.LEGACY_AUDIT_LOG (
    ID         INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    ACTION     VARCHAR(50),
    TABLE_NAME VARCHAR(100),
    LOGGED_AT  TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

CREATE INDEX DEMO_B.IDX_ORDERS_CUST ON DEMO_B.ORDERS(CUSTOMER_ID);

-- Case 5: composite index column order flipped (IP_ADDRESS first)
CREATE INDEX DEMO_B.IDX_PERF_COMPOSITE ON DEMO_B.WEB_LOGS(IP_ADDRESS, STATUS_CODE);

-- Orphan view (present in target, absent in source)
CREATE VIEW DEMO_B.V_ORDER_SUMMARY AS
SELECT o.id, o.total, o.status, o.created_at,
       oi.qty, oi.unit_price
FROM   DEMO_B.ORDERS o
JOIN   DEMO_B.ORDER_ITEMS oi ON oi.order_id = o.id;
