/**
 * Fox Schema (@foxschema/sql)
 * Copyright 2024-2026 Huy Phan <huyplb@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 *
 * What a dialect needs before it will accept an explicit value for an identity
 * / auto-increment column.
 *
 * This is the "Include identity" switch on data migrate — preserve the source
 * row's id rather than let the destination allocate a new one. A plain
 * `INSERT INTO t (id, …)` is enough on some engines and rejected outright on
 * others, so the statement has to be shaped per dialect.
 *
 * Two things make this worth a capability rather than a special case:
 *
 *  1. **The failure is at the database, not here.** SQL Server answers Msg 544;
 *     Postgres 428C9; Db2 SQL0798N; Oracle ORA-32795. Discovering that from a
 *     driver error, mid-migration, is the worst time to learn it.
 *  2. **Succeeding is not the end of it.** Where a sequence backs the column,
 *     an explicit insert does *not* advance it, so the destination keeps
 *     handing out ids that already exist. The migration reports success and the
 *     application starts failing later. See {@link IdentityInsertSupport.resyncSequence}.
 */

export type IdentityInsertKind =
  /** Explicit values are accepted as-is. */
  | 'native'
  /** Statement needs an `OVERRIDING SYSTEM VALUE` clause. */
  | 'overriding'
  /** Session must be toggled around the insert (`SET IDENTITY_INSERT`). */
  | 'toggle'
  /** No supported way to write the column explicitly. */
  | 'unsupported';

export interface IdentityInsertSupport {
  kind: IdentityInsertKind;
  /**
   * Clause to place after the column list, for `kind: 'overriding'`.
   *
   * Only valid on a column the engine actually treats as an identity — using
   * it elsewhere is itself an error, so callers must apply it per column, not
   * per statement.
   */
  clause?: string;
  /** Statement to run before the insert, for `kind: 'toggle'`. */
  enable?: (quotedTable: string) => string;
  /** Statement to run after, for `kind: 'toggle'`. */
  disable?: (quotedTable: string) => string;
  /**
   * True when a successful explicit insert leaves the generator behind.
   *
   * Sequence-backed engines (Postgres, Oracle, Db2) keep their counter where it
   * was, so the next generated id collides with a row just inserted. MySQL and
   * SQL Server move their counter past the value written, so they do not.
   *
   * This is the quiet one: nothing fails during the migration.
   */
  resyncSequence: boolean;
  /** Why, when `kind: 'unsupported'` — shown to the user, so it must be plain. */
  reason?: string;
}

const NATIVE: IdentityInsertSupport = { kind: 'native', resyncSequence: false };

/** Postgres family: `OVERRIDING SYSTEM VALUE`, sequence left behind. */
const OVERRIDING: IdentityInsertSupport = {
  kind: 'overriding',
  clause: 'OVERRIDING SYSTEM VALUE',
  resyncSequence: true,
};

/** SQL Server family: session toggle, one table at a time, counter self-heals. */
const TOGGLE: IdentityInsertSupport = {
  kind: 'toggle',
  enable: (t) => `SET IDENTITY_INSERT ${t} ON`,
  disable: (t) => `SET IDENTITY_INSERT ${t} OFF`,
  resyncSequence: false,
};

const SUPPORT: Record<string, IdentityInsertSupport> = {
  // AUTO_INCREMENT takes an explicit value, and the counter moves up to it.
  mysql: NATIVE,
  mariadb: NATIVE,
  tidb: NATIVE,
  // INTEGER PRIMARY KEY [AUTOINCREMENT] likewise.
  sqlite: NATIVE,
  // No identity concept that blocks a written value.
  clickhouse: NATIVE,
  duckdb: NATIVE,

  postgres: OVERRIDING,
  cockroachdb: OVERRIDING,
  yugabytedb: OVERRIDING,

  // Not OVERRIDING: that clause is Postgres (and DB2 for i / z/OS). Verified on
  // DB2 LUW 11.5 — `OVERRIDING SYSTEM VALUE` is SQL0104N in every position
  // (before the column list, after it, and on INSERT … SELECT), and a plain
  // insert into GENERATED ALWAYS is SQL0798N. There is no override, so listing
  // DB2 as `overriding` let the copy start and then fail mid-run, which is the
  // one outcome this table exists to prevent.
  db2: {
    kind: 'unsupported',
    resyncSequence: true,
    reason:
      'Db2 has no overriding clause for a GENERATED ALWAYS identity column ' +
      '(SQL0798N, and SQL0104N for OVERRIDING SYSTEM VALUE). Turn off Include ' +
      'identity, or change the column to GENERATED BY DEFAULT.',
  },

  sqlserver: TOGGLE,
  azuresql: TOGGLE,

  // Oracle has no overriding clause: GENERATED ALWAYS refuses an explicit
  // value and the only ways round it are altering the column or not writing
  // it. GENERATED BY DEFAULT does accept one — see identityInsertFor.
  oracle: {
    kind: 'unsupported',
    resyncSequence: true,
    reason:
      'Oracle rejects an explicit value for a GENERATED ALWAYS identity column ' +
      '(ORA-32795) and has no overriding clause. Turn off Include identity, or ' +
      'change the column to GENERATED BY DEFAULT.',
  },
  // Redshift IDENTITY columns cannot be written at all.
  redshift: {
    kind: 'unsupported',
    resyncSequence: false,
    reason:
      'Redshift does not allow writing an IDENTITY column. Turn off Include ' +
      'identity and let the destination assign values.',
  },
};

/**
 * Support for a dialect, ignoring how the specific column was declared.
 *
 * Unknown dialects fall to `unsupported` rather than `native`: guessing wrong
 * here writes an explicit id that the engine may or may not honour, and the
 * conservative answer only costs the user a switched-off toggle.
 */
export function identityInsertSupport(dialect: string): IdentityInsertSupport {
  return (
    SUPPORT[String(dialect).toLowerCase()] ?? {
      kind: 'unsupported',
      resyncSequence: false,
      reason: `Explicit identity inserts are not known to be supported on "${dialect}".`,
    }
  );
}

/**
 * Support for one column, given how it was declared.
 *
 * `identityGeneration` comes from the schema providers as `'ALWAYS'` or
 * `'BY DEFAULT'`. The distinction matters: a `BY DEFAULT` column accepts an
 * explicit value everywhere that has the concept, including Oracle, and needs
 * no overriding clause on Postgres or Db2.
 *
 * Note the providers are not uniform about this — SQL Server and Oracle report
 * every identity column as `'ALWAYS'`. For SQL Server that is right in effect
 * (there is no BY DEFAULT, and IDENTITY_INSERT is always required). For Oracle
 * it is over-strict: a genuine BY DEFAULT column is reported as ALWAYS and so
 * refused here. Refusing a migration that would have worked is the safe
 * direction, but it is a limitation, not a design.
 */
export function identityInsertFor(
  dialect: string,
  identityGeneration: string | undefined
): IdentityInsertSupport {
  const support = identityInsertSupport(dialect);
  const byDefault = String(identityGeneration ?? '').toUpperCase() === 'BY DEFAULT';
  if (!byDefault) return support;

  // BY DEFAULT: the value is accepted without ceremony. The sequence still
  // does not advance, so the resync warning stands.
  if (support.kind === 'overriding' || support.kind === 'unsupported') {
    return { kind: 'native', resyncSequence: support.resyncSequence };
  }
  return support;
}
