import { describe, expect, it } from 'vitest';
import { identityInsertFor, identityInsertSupport } from './identity-insert.js';
import { DIALECT_MAP } from './registry.js';

describe('identityInsertSupport — every registered dialect has an answer', () => {
  it('covers the whole registry', () => {
    // A dialect added later must not silently fall through to a guess.
    for (const dialect of Object.keys(DIALECT_MAP)) {
      const support = identityInsertSupport(dialect);
      expect(['native', 'overriding', 'toggle', 'unsupported'], dialect).toContain(support.kind);
      if (support.kind === 'unsupported') {
        // The reason is shown to a user mid-migration; it has to say what to do.
        expect(support.reason, dialect).toBeTruthy();
      }
    }
  });

  it('classifies each family the way the engine behaves', () => {
    for (const d of ['mysql', 'mariadb', 'tidb', 'sqlite']) {
      expect(identityInsertSupport(d).kind, d).toBe('native');
    }
    for (const d of ['postgres', 'cockroachdb', 'yugabytedb']) {
      expect(identityInsertSupport(d).kind, d).toBe('overriding');
      expect(identityInsertSupport(d).clause, d).toBe('OVERRIDING SYSTEM VALUE');
    }
    // Db2 is deliberately not in that list. It looks like Postgres from the
    // error message alone (both complain about GENERATED ALWAYS), but verified
    // on Db2 LUW 11.5: OVERRIDING SYSTEM VALUE is SQL0104N in every position,
    // so there is no ceremony that makes the write legal.
    expect(identityInsertSupport('db2').kind).toBe('unsupported');
    for (const d of ['sqlserver', 'azuresql']) {
      expect(identityInsertSupport(d).kind, d).toBe('toggle');
    }
    for (const d of ['oracle', 'redshift']) {
      expect(identityInsertSupport(d).kind, d).toBe('unsupported');
    }
  });

  it('emits the SQL Server toggle around the given table', () => {
    const s = identityInsertSupport('sqlserver');
    expect(s.enable?.('[dbo].[users]')).toBe('SET IDENTITY_INSERT [dbo].[users] ON');
    expect(s.disable?.('[dbo].[users]')).toBe('SET IDENTITY_INSERT [dbo].[users] OFF');
  });

  it('flags exactly the engines whose sequence is left behind', () => {
    // The quiet failure: insert succeeds, generator does not move, the next
    // application insert collides. Postgres/Oracle/Db2 yes; MySQL/SQL Server no.
    for (const d of ['postgres', 'cockroachdb', 'yugabytedb', 'db2', 'oracle']) {
      expect(identityInsertSupport(d).resyncSequence, d).toBe(true);
    }
    for (const d of ['mysql', 'mariadb', 'tidb', 'sqlite', 'sqlserver', 'azuresql']) {
      expect(identityInsertSupport(d).resyncSequence, d).toBe(false);
    }
  });

  it('refuses an unknown dialect rather than assuming it is fine', () => {
    const s = identityInsertSupport('some-future-engine');
    expect(s.kind).toBe('unsupported');
    expect(s.reason).toContain('some-future-engine');
  });

  it('is case-insensitive about the dialect name', () => {
    // DIALECT_MAP keys are uppercase ('POSTGRES'), while connections carry
    // lowercase ids — both have to resolve to the same answer.
    expect(identityInsertSupport('POSTGRES').kind).toBe('overriding');
    expect(identityInsertSupport('postgres').kind).toBe('overriding');
    expect(identityInsertSupport('SqlServer').kind).toBe('toggle');
  });
});

describe('identityInsertFor — how the column was declared', () => {
  it('drops the overriding clause for a BY DEFAULT column', () => {
    // GENERATED BY DEFAULT takes an explicit value with no ceremony.
    expect(identityInsertFor('postgres', 'BY DEFAULT').kind).toBe('native');
    expect(identityInsertFor('db2', 'BY DEFAULT').kind).toBe('native');
  });

  it('keeps the overriding clause for ALWAYS', () => {
    expect(identityInsertFor('postgres', 'ALWAYS').kind).toBe('overriding');
  });

  it('refuses a Db2 GENERATED ALWAYS identity outright', () => {
    // Letting this through as `overriding` started the copy and then failed it
    // mid-run with SQL0104N — the outcome this table exists to prevent.
    const always = identityInsertFor('db2', 'ALWAYS');
    expect(always.kind).toBe('unsupported');
    expect(always.reason).toMatch(/GENERATED BY DEFAULT/i);
    // BY DEFAULT is genuinely writable — confirmed against the live server.
    expect(identityInsertFor('db2', 'BY DEFAULT').kind).toBe('native');
  });

  it('lets Oracle BY DEFAULT through', () => {
    // Oracle only refuses GENERATED ALWAYS; BY DEFAULT is writable.
    expect(identityInsertFor('oracle', 'ALWAYS').kind).toBe('unsupported');
    expect(identityInsertFor('oracle', 'BY DEFAULT').kind).toBe('native');
  });

  it('keeps the sequence warning even when the clause is dropped', () => {
    // BY DEFAULT still does not advance the sequence — this is the trap.
    expect(identityInsertFor('postgres', 'BY DEFAULT').resyncSequence).toBe(true);
    expect(identityInsertFor('oracle', 'BY DEFAULT').resyncSequence).toBe(true);
  });

  it('still needs the toggle on SQL Server whatever the column says', () => {
    // SQL Server has no BY DEFAULT; IDENTITY_INSERT is required regardless.
    expect(identityInsertFor('sqlserver', 'BY DEFAULT').kind).toBe('toggle');
    expect(identityInsertFor('sqlserver', 'ALWAYS').kind).toBe('toggle');
  });

  it('treats a missing generation as the strict case', () => {
    expect(identityInsertFor('postgres', undefined).kind).toBe('overriding');
    expect(identityInsertFor('oracle', undefined).kind).toBe('unsupported');
  });
});
